version: "3.3"

services: 
  demo-api-inventory-clean-architecture:
    restart: always 
    ports:
      - "6000:6500"
    build: .
    environment:
      - URL_PG_DATABASE_MASTER=${URL_PG_DATABASE_MASTER}
      - URL_REDIS_SERVER=${URL_REDIS_SERVER}
      - URL_WH_APP_FW_PRODUCT_01GE=${URL_WH_APP_FW_PRODUCT_01GE}
      - N8N_API_KEY=${N8N_API_KEY}
    networks:
      - inventory_network
    links:
      - postgres
      - redis
  postgres:
    container_name: postgres_db
    restart: always
    image: "postgres:14"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - inventory_network
    volumes:
      - 'postgresql_master_data:/internal/postgresql'
    ports:
      - "7000:5432"
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${DOCKER_INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_HOST=${DOCKER_INFLUXDB_INIT_HOST}
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - '8086:8086'
    networks:
      - inventory_network
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    depends_on:
      - influxdb
    user: "root"
    entrypoint: /bin/bash -c "chmod 777 /var/run/docker.sock && /entrypoint.sh telegraf"
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/hostfs:ro
    networks:
      - inventory_network
  redis:
    container_name: redis_db
    restart: always
    image: "redis:6.0.16"
    networks:
      - inventory_network
    ports: 
      - "8000:6379"
networks:
  inventory_network:
    driver: bridge
    ipam: 
      driver: default 
volumes:
  postgresql_master_data: